apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-app
  labels:
    app: financial-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-app
  template:
    metadata:
      labels:
        app: financial-app
    spec:
      containers:
      - name: financial-app
        image: karthik7756/financial-transaction-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
